let express=require('express')
const { indexHandler, adminHandler, adminDataHandler, facultyHandler, facultyDeleteHandler, editFacultyHandlerData, adminDataEditHandler } = require('../controller/facultyController')
let route=express.Router()
route.get('/',indexHandler)
route.get('/admin',adminHandler)
route.post('/admin',adminDataHandler)
route.put('/admin/:id',adminDataEditHandler)
route.get('/faculty',facultyHandler)
route.delete('/faculty/:id',facultyDeleteHandler)
route.get(`/edit/:id`,editFacultyHandlerData)
module.exports=route